axel_width   : 0.233
axel_length  : 0.142
wheel_radius : 0.0635

sensor_base:
  publish_rate: 50

drive_base:
  dev           : /dev/ttyUSB0
  baud_rate     : 38400
  rear_address  : 129
  front_address : 128
  tick_per_meter: 5413.17  # gear_ration * pulse_per_rev / (2 * PI * wheel_radius) = 45 * 48 / (2.0 * 3.141592 * 0.0635)
  diagnostic    : false